---
- name: Adding APT repository key
  become: yes
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: Add PostgreSQL official APT repository
  become: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"

- name: Install PostgreSQL
  become: yes
  apt:
    name: "postgresql-9.5"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Install dependencies for the Ansible module
  become: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-psycopg2


- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db: name='{{ item }}' encoding='UTF-8' lc_collate='en_US.UTF-8'  lc_ctype='en_US.UTF-8' template='template0' state=present
  with_items:
   - human-ivr
   - human-ivr-security

- name: Ensure user is created and does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} role_attr_flags=NOSUPERUSER,NOCREATEDB,LOGIN,NOREPLICATION,NOCREATEROLE,INHERIT state=present

