---
- name: Install PostgreSQL
  apt: name={{ item }} update_cache=true state=installed
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  become: true
  become_user: postgres
  postgresql_db: name='{{ item }}' encoding='UTF-8' lc_collate='en_US.UTF-8'  lc_ctype='en_US.UTF-8' template='template0' state=present
  with_items:
   - human-ivr
   - human-ivr-security

- name: Ensure user is created and does not have unnecessary privileges
  become: true
  become_user: postgres
  postgresql_user: name={{ db_user }} password={{ db_password }} role_attr_flags=NOSUPERUSER,NOCREATEDB,LOGIN,NOREPLICATION,NOCREATEROLE,INHERIT state=present

