---
# Default variables - inventory or playbook overrides will be respected


# tomcat8 specific variables
tomcat8_binary_download_url: http://archive.apache.org/dist/tomcat/tomcat-8/v8.5.6/bin/apache-tomcat-8.5.6.tar.gz

tomcat8_firewall_port_http: 8080
