---
# Configure Tomcat installation

- name: set tomcat user as owner and adm group as group for tomcat directories
  file:
       path="{{ item }}"
      owner=tomcat
      group=adm
    recurse=yes
  with_items:
    - /opt/tomcat8/conf
    - /opt/tomcat8/logs
    - /opt/tomcat8/temp
    - /opt/tomcat8/work
    - /opt/tomcat8/webapps

- name: set permissions for tomcat configuration files
  file:
    path="/opt/tomcat8/conf"
    mode=u+rw,g+rw
    recurse=yes
    state=directory

- name: ensure conventional locations exist for linking to tomcat directories
  file:
    path="{{ item }}"
    state=directory
  with_items:
    - /etc/tomcat8
    - /var/lib/tomcat8

- name: create symlinks to link conventional locations to tomcat directories
  file:
      src="{{ item.src }}"
     path="{{ item.path }}"
    state=link
  with_items:
    -
      src: /opt/tomcat8/conf
      path: /etc/tomcat8/conf
    -
      src: /opt/tomcat8/logs
      path: /var/log/tomcat8
    -
      src: /opt/tomcat8/webapps
      path: /var/lib/tomcat8/webapps

- name: generate upstart script for tomcat 8 - Ubuntu
  template:
     src=etc/init/tomcat8.conf.j2
    dest=/etc/init/tomcat8.conf
  notify:
    - Reload Upstart Daemon - Ubuntu
    - Start Tomcat

