---
# Create a firewall service for tomcat 8 to configure the system firewall

- name: generate firewall service for tomcat 8 - Ubuntu/UFW
  template:
     src=etc/ufw/applications.d/tomcat8.j2
    dest=/etc/ufw/applications.d/tomcat8
  when: ansible_distribution == "Ubuntu"

- name: configure firewall rules for tomcat 8 service - Ubuntu/UFW
  ufw:
         name="tomcat8-http"
         rule=allow
    direction=in
  when: ansible_distribution == "Ubuntu"
  notify: Restart Firewall - Ubuntu
